### ISSUE TITLE
missing cluster error handling

### ISSUE THREAD

**Issue by eguzki** [Kuadrant/wasm-shim#123]
When the service endpoint does not exist from the defined set of envoy clusters.

```json
"services": {
  "mistyped-service": {
    "type": "ratelimit",
    "endpoint": "does-not-exist",
    "failureMode": "deny"
  }
},
"actionSets": [
{
    "actions": [
        {
            "service": "mistyped-service",
            "scope": "b",
            "data": [
                {
                    "expression": {
                        "key": "limit_to_be_activated",
                        "value": "1"
                    }
                }
            ]
        }
    ]
}
]
```

Then, the request will `Continue` regardless of `failureMode` config. 

I have implemented an e2e test that reproduces this issue: https://github.com/Kuadrant/wasm-shim/pull/122

**Comment by didierofrivia** [comment]
I'm a bit confused, since https://github.com/Kuadrant/wasm-shim/pull/122 is about parallel requests to envoy and this issue is about error handling? The implementation of the operation dispatcher is a basic one, I agree we need error handling (among other things), but mistyped configuration would kind of be a thing coming from the Kuadrant Operator.
In any case, if a given request to a service fails, we should follow the `failureMode` config for that service and Allow/Deny respectively **or** define a set of operations to follow depending on the service? (i.e: retry, authorize, limit...etc)

**Comment by eguzki** [comment]
> In any case, if a given request to a service fails, we should follow the failureMode config for that service and Allow/Deny respectively or define a set of operations to follow depending on the service? 

I would say follow the `failureMode`. :shrug:
